language: node_js
node_js:
- node
- '6'
- '4'
addons:
  code_climate:
    repo_token: 0833cf69acc3ad4c6f78ea7fac4b1b2520d8f8484b20ed8c114468864bb7ab2c
notifications:
  email: false
  slack:
    rooms:
      secure: l2F0EWyUmlXHXqPdsF6oP+FOHgw0db+co3M9mBfX8eXXthY9wjgAoeBGvikiC6PB77bbe3YLWidS622KfaCzCCoBmg91StTauE0UexZmeZJQHPxJkckMY5eTaRcNIoP50HA+G7Rn96XJRcDOXZOzjYxOCv+BUqi3YMGB81KN2pcUZXJlftDY22nsxqqi85cfqK9cXkQRAlKHEOz1i/wP8lQi2i+n314bzwwYSH5t5FNJTPobxtMrBNEKdZHQKjb3E0KC8XlZyQAaFPMgI9brMIeAEKmGazMsNyIKqu9Psd8QrDHDwF5fEHzqHPW5Cc2kQusHzLYAoPVxnw6HSJxeUqKXESmCB4apm6X38fy6Oz8oRf7G/ilqvKkhkLtkl7+HH3XU5h3dNj+IC7YcN7cB5Z6lJ7b7UFja9Sueg+u2OG8aC6fPT6tbJIL/s36OUWZAZFtlfmQ+cF/xL0Gx4mnhTsD7UPoi62wG+Ruc7ZfXXuuztZSQ7cpAN9sN7fsw0vNvkTb1tVgh2eswYnG32mRnl3akCpHmJHtf+4xMHB3FQTJ2+2vmkogASjBknVJWghvL+YsoHAcUdb2Gg5WZfotDEGhQwbLpwsHIrXPie9GdrOLRUY0BHb73RPssbwT6ohMqaA6zwrlUhhuevW9Z5dv6QMJ7VAhJrlG5whE7TGTgWR8=
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info